/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkpassdata_Dataprovider */

#ifndef _Included_com_example_ndkpassdata_Dataprovider
#define _Included_com_example_ndkpassdata_Dataprovider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkpassdata_Dataprovider
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndkpassdata_Dataprovider_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_ndkpassdata_Dataprovider
 * Method:    sayHelloInC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndkpassdata_Dataprovider_sayHelloInC
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_ndkpassdata_Dataprovider
 * Method:    intMethod
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_ndkpassdata_Dataprovider_intMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
